# close without confirmation
confirm-before-quit = false

# theme
theme = 'catppuccin-mocha'

hide-mouse-cursor-when-typing = false
option-as-alt = 'right'

# working-dir = 'None'
# Window padding
padding-x = 10
padding-y = [-15, 10]

[editor]
program = 'vi'
args = []

[cursor]
shape = 'block'
blinking = false

[fonts]
family = 'JetBrainsMono Nerd Font'
size = 16.0
hinting = true

[fonts.ui]
family = 'JetBrainsMono Nerd Font'

[shell]
program = '/bin/zsh'
args = ['--login']
# program = '/opt/homebrew/bin/tmux'
# args = ['new-session', '-A', '-s', 'default']

[renderer]
performance = 'High'
backend = 'Automatic'
target-fps = 120
strategy = 'events'

[window]
mode = 'Windowed'
opacity = 0.85
blur = true
decorations = 'Buttonless'

[keyboard]
disable-ctlseqs-alt = false

[navigation]
mode = 'Plain'
hide-if-single = true
