# enable_rgb = true
live_config_reload = true
working_directory = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "screen-256color"

[font]
builtin_box_drawing = true
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.92
startup_mode = "SimpleFullscreen"
#tabspace = 4

[window.padding]
x = 16
y = 16
